### ISSUE TITLE
There is something wrong with libDA.so

### ISSUE THREAD

**Issue by zzxp** [rdguez-mariano/sift-aid#3]
Hi！I encountered some difficulties when build sift-aid with a libDA that i generated. The error
is "OSError: [WinError 193] %1".I have no idea with the error,because libDA.so is 64 bit and also with sift-aid. Could you give me some suggestions or share your libDA.so?
Look forward to hearing from you！

**Comment by rdguez-mariano** [comment]
Hi there !
Sounds like libDA haven't compiled properly. How did you compiled it in windows ? Could you send the compiling logs ? For example, there's this post here
https://stackoverflow.com/questions/21387504/cmake-and-make-in-windows 
that could help you out.
Please also let us know if you solved the compiling issues in Windows!
Best,
Mariano

**Comment by zzxp** [comment]
Sorry to reply you now，I was compiled libDA in linux，and then used libDA.so in windows. Because the code interface is for  libDA.so, not libDA.dll. This way doesn't seem to work.

**Comment by zzxp** [comment]
this is the compiling logs:
The system is: Linux - 4.15.0-54-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/zouz/sift-aid-master/build/CMakeFiles/3.5.1/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: 
Id flags: 

The output was:
0

**Comment by zzxp** [comment]
I have solved this problem, compiled with mingw64, and generated a callable libDA.dll
